// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/anle/codebase/internal/controller"
	"github.com/anle/codebase/internal/repo"
	"github.com/anle/codebase/internal/services"
)

// Injectors from authen.wire.go:

func InitAuthenRouterHandler() (*controller.AuthenController, error) {
	iAuthenRepo := repo.NewAuthenRepo()
	iAuthenService := service.NewAuthenService(iAuthenRepo)
	authenController := controller.NewAuthenController(iAuthenService)
	return authenController, nil
}
