// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/anle/codebase/internal/controller"
	"github.com/anle/codebase/internal/repo"
	"github.com/anle/codebase/internal/service"
)

// Injectors from authen.wire.go:

func InitAuthenRouterHandler(dbc *sql.DB) (*controller.AuthenController, error) {
	iAuthenRepo := repo.NewAuthenRepo(dbc)
	iAuthenService := service.NewAuthenService(iAuthenRepo)
	authenController := controller.NewAuthenController(iAuthenService)
	return authenController, nil
}
